ARG IMG_NAME=${$IMG_NAME:-gradle}
ARG IMG_TAG=${$IMG_TAG:-latest}

FROM ${IMG_NAME}:${IMG_TAG}

ARG IMG_NAME=${IMG_NAME:-debian}
ARG IMG_TAG=${IMG_TAG:-latest}
ARG TIMEZONE=${TIMEZONE:-UTC}

ARG DEBIAN_FRONTEND=noninteractive

ENV TZ="${TIMEZONE}"

RUN apt-get -qq -y update && apt-get -qq -y upgrade \
    && apt-get -qq -y install \
        vim \
        curl \
        wget \
        apt-transport-https \
        sudo \
        git \
        tzdata \
        bash \
        maven \ 
        zip \
    && ln -fs /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
    && dpkg-reconfigure -f noninteractive tzdata

WORKDIR /home/gradle/project
USER gradle

VOLUME [ "/home/gradle", "/opt" ]
CMD [ "bash" ]