/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        StringBuilder sb = new StringBuilder("Hello World!");
        return sb.toString() + " | " + sb.reverse().toString();
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
